### PR TITLE
OLD - Prepare Trappist v1.3.0 release 

### PR DESCRIPTION
**Pull request by metricaez**

### CODE REVIEW

**Comment by stiiifff** [comment]
bot bench-all trappist

**Comment by metricaez** [comment]
Note: [8f098de](https://github.com/paritytech/trappist/pull/319/commits/8f098def5e7479caaa4064219054a383385904f0) adds a benchmark helper needed to generate an existencial deposit for the beneficiary created for the benchmark. `pallet_treasury` benchmark by default transfers [100 tokens](https://github.com/paritytech/polkadot-sdk/blob/3e4e8c0bd1b1487c47c95dc27f2fff9e2f4e7fa0/substrate/frame/treasury/src/benchmarking.rs#L104) and in Trappist's case it didn't meet minimum balance triggering a `Payout Error` shadowing a `BelowMinimum` token error.

**Comment by metricaez** [comment]
bot bench-all trappist

**Comment by metricaez** [comment]
bot bench-all trappist

**Comment by metricaez** [comment]
Note: These assets are now being considered [here](https://github.com/paritytech/polkadot-sdk/blob/792e374395078ee571bf14e4d7e09e753b79e819/polkadot/xcm/pallet-xcm-benchmarks/src/fungible/benchmarking.rs#L99C2-L99C2). Therefore the reason of it causing problems now even though it's been months with the same setup.

**Comment by metricaez** [comment]
bot bench-all trappist

**Comment by metricaez** [comment]
Closing as benchmarks were passing because I changed them to the ones from balances, even though the issue is the one stated, the solution is incorrect and reverting would add yet more unnecessary info. Opening a new PR now.

**Pull request closed without merging**
