### PR TITLE
Use XCM benchmarks from `pallet_xcm_benchmarks`

### LINKED ISSUE #182: Use XCM benchmarks from `pallet_xcm_benchmarks`
At the moment we are hardcoding the XCM weights using the `FixedWeightBounds` with the following configuration:

```rust
parameter_types! {
	// One XCM operation is 1_000_000_000 weight - almost certainly a conservative estimate.
	pub UnitWeightCost: u64 = 1_000_000_000;
	pub const MaxInstructions: u32 = 100;
}

...

pub struct XcmConfig;
impl xcm_executor::Config for XcmConfig {
...
    type Weigher = FixedWeightBounds<UnitWeightCost, RuntimeCall, MaxInstructions>;
...
}

impl pallet_xcm::Config for XcmConfig {
...
    type Weigher = FixedWeightBounds<UnitWeightCost, RuntimeCall, MaxInstructions>;
...
}
```

We should replace the `FixedWeightBounds` with  `WeightInfoBounds` and use the weights resulting from the `pallet_xcm_benchmarks`. From the runtime perspective, there are some changes that are needed over the `define_benchmarks!` and `impl frame_benchmarking::Benchmark<Block> for Runtime `. Here is the example for Statemine configuration:

https://github.com/paritytech/cumulus/blob/polkadot-v0.9.37/parachains/runtimes/assets/statemine/src/lib.rs#L850

This change should be back ported into branch `xcmv3-dev` as well.

### LINKED ISSUE #183: XCM Config: Rename `Statemine` references to Rockmine and fix minor details in XCM config.
At the moment the xcm_config.rs, contains references to `Statemine` and `NetworkId::Polkadot`. 

As in Rococo, the asset common good parachain is called Rockmine, it's more consistent to rename the xcm config to Rockmine. Also in XCM v2, there is no `NetworkId::Rococo`, so initially this should be set to `Any` and in XCM v3, use the right value.

### PR DESCRIPTION
**Pull request by hbulgarini**
This PR is adding the XCM weights from the `pallet_xcm_benchmarks` as it's configured in Statemine. The weights file pushed in this PR are just copy/paste from Statemine directory since we are waiting the benchmark bot execution which is being worked in the issue #141 . 

As well this PR address the minor details from issue #183 , which should not affect any functioning since it is mostly a renaming. In case the team agrees to move this change out of this PR, i can do it with no issues.

Closes #182 
Closes #183 

Note: This PR is in Draft mode and it serves as a documentation for the moment.

### CODE REVIEW

**Comment by hbulgarini** [comment]
@kalaninja the tests are failing in the CI even when locally they run fine. Could you please check if something is missing in my branch? (i know you were tweaking this lately)

**Comment by valentinfernandez1** [comment]
I am also encountering the error and it seems like it is related to the Ubuntu machine running the CI that runs out of memory.

**Comment by kalaninja** [comment]
> @kalaninja the tests are failing in the CI even when locally they run fine. Could you please check if something is missing in my branch? (i know you were tweaking this lately)

done

**Comment by hbulgarini** [comment]
> > @kalaninja the tests are failing in the CI even when locally they run fine. Could you please check if something is missing in my branch? (i know you were tweaking this lately)
> 
> done

Thanks man you are the # 1

**Review by kalaninja — APPROVED** [review]

**Pull request merged**
