### PR TITLE
Regenerate weights for 0.9.42

### LINKED ISSUE #251: [0.9.42] Generate new weights
After the upgade to 0.9.42 weights have to be regenerated.

### PR DESCRIPTION
**Pull request by kalaninja**
Regenerate weights after upgrade to 0.9.42.

resolves #251

### CODE REVIEW

**Comment by kalaninja** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround $ trappist

**Comment by kalaninja** [comment]
bot bench-all trappist -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by kalaninja** [comment]
bot clean

**Comment by kalaninja** [comment]
bot bench-all trappist-all -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by kalaninja** [comment]
bot bench-all trappist-all -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by kalaninja** [comment]
bot bench-all trappist -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by kalaninja** [comment]
bot bench-all trappist -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround --target_dir=trappist

**Comment by kalaninja** [comment]
bot clean

**Comment by kalaninja** [comment]
bot bench-all trappist -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by kalaninja** [comment]
bot bench-all trappist -v PIPELINE_SCRIPTS_REF=feature/remove-trappist-workaround

**Comment by hbulgarini** [comment]
Are the very big reductions in ref_time on all pallets due to the new hardware? I saw the  i7 replaced by Xeon CPU’s

**Review by hbulgarini — APPROVED** [review]

**Comment by kalaninja** [comment]
@hbulgarini the previous weights were generated on my machine, now I am changing it with the proper ones

**Pull request merged**
