### PR TITLE
Prepare Trappist v1.1.0 release

### PR DESCRIPTION
**Pull request by stiiifff**

### CODE REVIEW

**Comment by stiiifff** [comment]
bot bench-all trappist

**Comment by stiiifff** [comment]
bot bench-all trappist

**Comment by metricaez** [comment]
bot bench-all trappist

**Comment by stiiifff** [comment]
bot bench-all trappist

**Comment by pgherveou** [comment]
You need to set `type MaxHolds` on pallet_balances Config to some non 0 value here, or pallet_contracts fails to hold some balance for uploading new contracts, and you end up with the error StorageDepositNotEnoughFunds from the jobs log. 

Will add some more warn in the pallet_contracts logs to make this more obvious!

**Comment by metricaez** [comment]
bot bench-all trappist

**Comment by stiiifff** [comment]
Ignoring the `try-runtime` check error, as there's effectively is no runtime migration in this release.

**Comment by Moliholy** [comment]
> Ignoring the `try-runtime` check error, as there's effectively is no runtime migration in this release.

I just run the migration and it turns out `pallet-contracts` in at version 12 instead of 15. That's, as you've mentioned, not supposed to be that way, because trappist was migrated in the past to version 15. However, try-runtime says otherwise. I think it'd be wise to further research this issue.

Furthermore, when running try-runtime with the `try-state` flag, I discovered there's data corruption in `pallet-collective`. An extra migration would be needed to solve this issue.

**Comment by metricaez** [comment]
Ignoring try-runtime error as it is non breaking while we debug it.

**Review by metricaez — DISMISSED** [review]

**Comment by metricaez** [comment]
bot bench-all trappist

**Review by metricaez — APPROVED** [review]

**Review by metricaez — APPROVED** [review]

**Comment by stiiifff** [comment]
LGTM !

**Pull request merged**
