### PR TITLE
Missing storage migrations

### PR DESCRIPTION
**Pull request by hbulgarini**
The result of `try-runtime` dropped some missing storage migrations.
`PolkadotXcm` and `Scheduler` should be changed but for the rest i think there are false alarms since the live version is already  running with the same version or even higher so they can be false alarms:

``` 
✅ Inserted keys into DB (0.01s)
2023-08-21 23:34:36.717  INFO main remote-ext: adding data for hashed prefix: , took 4.04s    
2023-08-21 23:34:36.717  INFO main remote-ext: adding data for hashed key: 3a636f6465    
2023-08-21 23:34:36.921  INFO main remote-ext: adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8    
2023-08-21 23:34:37.077  INFO main remote-ext: adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef702a5c1b19ab7a04f536c519aca4983ac    
2023-08-21 23:34:37.235  INFO main remote-ext: initialized state externalities with storage root 0x2da99150fe63dd8b90603f09346128a1f1376b1495fc33cdfdef48debaeac0d9 and state_version V1    
2023-08-21 23:34:37.421  INFO main try-runtime::cli: original spec: RuntimeString::Owned("trappist-rococo")-9420, code hash: 8f3d76fee97f564b91b42a696bee455c65750a9e5ea36d9a867bc20f9f35c798    
2023-08-21 23:34:37.576  INFO main try-runtime::cli: new spec: RuntimeString::Owned("trappist-rococo")-9430, code hash: 02730d6f7c81b3207ac27b02b8cbfb165af23d0c4c5aa2823d639e12064b8a73    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for System    
2023-08-21 23:34:43.697  INFO main runtime::frame-support: ⚠️ ParachainSystem declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(2)`    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for RandomnessCollectiveFlip    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Timestamp    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for ParachainInfo    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Balances    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for TransactionPayment    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for AssetTxPayment    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Authorship    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for CollatorSelection    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Session    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Aura    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for AuraExt    
2023-08-21 23:34:43.697  INFO main runtime::frame-support: ⚠️ XcmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(3)` vs current storage version `StorageVersion(2)`    
2023-08-21 23:34:43.697 ERROR main runtime::frame-support: XcmpQueue: On chain storage version StorageVersion(3) doesn't match current storage version StorageVersion(2).    
2023-08-21 23:34:43.697  INFO main runtime::frame-support: ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(1)`    
2023-08-21 23:34:43.697 ERROR main runtime::frame-support: PolkadotXcm: On chain storage version StorageVersion(0) doesn't match current storage version StorageVersion(1).    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for CumulusXcm    
2023-08-21 23:34:43.697  INFO main runtime::frame-support: ⚠️ DmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(1)`    
2023-08-21 23:34:43.697 ERROR main runtime::frame-support: DmpQueue: On chain storage version StorageVersion(2) doesn't match current storage version StorageVersion(1).    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Contracts    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Assets    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Identity    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Uniques    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Scheduler    
2023-08-21 23:34:43.697 ERROR main runtime::frame-support: Scheduler: On chain storage version StorageVersion(3) doesn't match current storage version StorageVersion(4).    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Preimage    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for LockdownMode    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Utility    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Multisig    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Council    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Treasury    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Democracy    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Sudo    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for Dex    
2023-08-21 23:34:43.697 DEBUG main runtime::frame-support: ✅ no migration for AssetRegistry    
2023-08-21 23:34:43.697 ERROR main try-runtime: Detected multiple errors while executing `try_on_runtime_upgrade`:    
2023-08-21 23:34:43.697 ERROR main try-runtime: Other("On chain and current storage version do not match. Missing runtime upgrade?")    
2023-08-21 23:34:43.697 ERROR main try-runtime: Other("On chain and current storage version do not match. Missing runtime upgrade?")    
2023-08-21 23:34:43.697 ERROR main try-runtime: Other("On chain and current storage version do not match. Missing runtime upgrade?")    
2023-08-21 23:34:43.697 ERROR main try-runtime: Other("On chain and current storage version do not match. Missing runtime upgrade?")   
```

### CODE REVIEW

**Review by brunopgalvao — APPROVED** [review]
Similar to: https://github.com/paritytech/polkadot/pull/7251/files#diff-0d5d1f76b24989edd69c12c2f482abdf143d8926f1b3191665378b848515d45cR1539

**Comment by hbulgarini** [comment]
errors from DmpQueue and XcmpQueue are appearing because the storage migration from v1 to v2 and v2 to v3 respectively in release 0.9.42, but in the release 0.9.43 the storage items were not updated with the new upgraded storage versions.

One example:

0.9.43: https://github.com/paritytech/cumulus/blob/polkadot-v0.9.43/pallets/xcmp-queue/src/migration.rs#L27
1.0.0 : https://github.com/paritytech/cumulus/blob/polkadot-v1.0.0/pallets/xcmp-queue/src/migration.rs#L27

**Comment by brunopgalvao** [comment]
For time being, dismiss them.

**Comment by brunopgalvao** [comment]
bot try-runtime -v RUST_LOG=debug trappist --chain=trappist-dev --chain_node=rococo-trappist --target_path=. --live_uri=rococo-trappist

**Comment by brunopgalvao** [comment]
bot try-runtime -v RUST_LOG=debug trappist --chain=trappist --chain_node=rococo-trappist --target_path=. --live_uri=rococo-trappist

**Comment by brunopgalvao** [comment]
bot try-runtime -v RUST_LOG=debug trappist --chain=rococo --chain_node=rococo-trappist --target_path=. --live_uri=rococo-trappist

**Comment by brunopgalvao** [comment]
bot try-runtime trappist -v RUST_LOG=debug

**Pull request merged**
