### PR TITLE
Migrate to polkadot v1.0.0

### PR DESCRIPTION
**Pull request by Moliholy**
@hbulgarini this PR is based on your branch for the 0.9.43 migration. You can find the actual migration commit [here](https://github.com/paritytech/trappist/pull/262/commits/f7145f6ac4235319c486a934b10b55d2cc4a5b57).

### CODE REVIEW

**Comment by evilrobot-01** [comment]
A suggestion: perhaps update to use the monorepo before merging?

**Comment by hbulgarini** [comment]
> A suggestion: perhaps update to use the monorepo before merging?

if i'm not mistaken , monorepo will contain a newer release than polkadot 1.0 right?

**Comment by evilrobot-01** [comment]
> if i'm not mistaken , monorepo will contain a newer release than polkadot 1.0 right?

Not sure, assume it is simply the repo state as at the specific migration date.

I dont see any rush in going to 1.0, so it might be a good opportunity to update/test the mono repo in the next week rather than waiting for a future release. Just a thought.

**Comment by hbulgarini** [comment]
> I dont see any rush in going to 1.0, so it might be a good opportunity to update/test the mono repo in the next week rather than waiting for a future release. Just a thought.

I would like to have this finished at least by a couples of days prior to sub0.

@stiiifff what do you think?

**Comment by stiiifff** [comment]
@hbulgarini Yeah, let's complete the 1.0 upgrade. The mono-repo update came come later.

**Comment by hbulgarini** [comment]
> I guess the storage migration is failing for the exact same reason it already failed in the `0.9.43` migration. Isn't it, @hbulgarini ?

not really , for some reason this branch is not taking the the changes done on the PR #261 but it seems that there are new migrations included in Contacts and CollatorSelection pallets :/

**Comment by Moliholy** [comment]
> not really , for some reason this branch is not taking the the changes done on the PR #261 but it seems that there are new migrations included in Contacts and CollatorSelection pallets :/

I just added those commits to this PR. Let's see now.

**Comment by Moliholy** [comment]
Added [35e301e](https://github.com/paritytech/trappist/pull/262/commits/35e301e67fa19631f012dfade153d930ca1327a9) with missing migrations.

**Comment by hbulgarini** [comment]
bot bench-all trappist

**Comment by hbulgarini** [comment]
bot bench-all trappist

**Review by hbulgarini — APPROVED** [review]

**Pull request merged**
