### PR TITLE
Command bot test

### PR DESCRIPTION
**Pull request by alvicsam**

### CODE REVIEW

**Comment by alvicsam** [comment]
bot rebase

**Comment by alvicsam** [comment]
bot help

**Comment by alvicsam** [comment]
bot clean

**Comment by alvicsam** [comment]
bot bench-vm

**Comment by alvicsam** [comment]
bot clean

**Comment by kalaninja** [comment]
bot help

**Comment by kalaninja** [comment]
bot bench-all

**Comment by kalaninja** [comment]
bot help -v PIPELINE_SCRIPTS_REF=add-trappist

**Comment by kalaninja** [comment]
bot help -v PIPELINE_SCRIPTS_REF=kalaninja:add-trappist

**Comment by kalaninja** [comment]
bot help -v PIPELINE_SCRIPTS_REF=kalaninja:add-trappist

**Comment by kalaninja** [comment]
bot help -v PIPELINE_SCRIPTS_REF=add-trappist

**Comment by kalaninja** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=add-trappist $ trappist

**Comment by kalaninja** [comment]
bot clean

**Comment by kalaninja** [comment]
bot bench-all $ trappist

**Comment by kalaninja** [comment]
The bot seem to work fine.

**Pull request closed without merging**
