### PR TITLE
feat: use try-runtime-cli instead of command

### LINKED ISSUE #263: Use the standalone try-runtime CLI
Substrate’s [`try-runtime` subcommand](https://paritytech.github.io/substrate/master/try_runtime_cli/index.html) has been migrated to a [standalone CLI](https://github.com/paritytech/try-runtime-cli).
- https://github.com/paritytech/try-runtime-cli

Modify our Github Workflow to accommodate for this.

### PR DESCRIPTION
**Pull request by Moliholy**
Closes #263.

### CODE REVIEW

**Comment by hbulgarini** [comment]
nice @Moliholy ! thanks for this! 

quick question: Are the try-runtime sub commands defined in the node still necessary or we can clean them up?

https://github.com/paritytech/trappist/blob/main/node/src/command.rs#L390:L472

**Comment by Moliholy** [comment]
> quick question: Are the try-runtime sub commands defined in the node still necessary or we can clean them up?

@hbulgarini to be honest I wasn't totally sure we should remove the command just yet. Nothing in particular, I simply thought to take a conservative approach and leave both ways to run the try-runtime, just in case.

Anyhow, let's see what @brunopgalvao says.

**Comment by Moliholy** [comment]
> Three options that I see:
> 
> 1. Deprecation of the sub command similar to here:
> 
> * https://github.com/paritytech/substrate/pull/14731/files#diff-2596a1f06e9ff71a14b48a5a483ba93a76c1d10ead2dec9f1871895f28711d33
> 
> 2. Remove the sub command since it is working now with the standalone CLI
> 3. Remove the sub command in a later release
> 
> I am more in favor of 2.

Me too. I just added [209a91c](https://github.com/paritytech/trappist/pull/270/commits/209a91c01f3ee3025adbad75d9ed1a5755b73fb3) with the changes.

**Comment by Moliholy** [comment]
I also added [2d53a48](https://github.com/paritytech/trappist/pull/270/commits/2d53a48d72816ec07a62d0ad7dcce1c3559eae4b) to remove already applied migrations. Otherwise the migration test won't pass.

**Review by stiiifff — APPROVED** [review]

**Pull request merged**
